In [2]:
with open(r'C:\Users\natas\Downloads\UNZIP_FOR_NOTEBOOKS_FINAL\18-Naive-Bayes-and-NLP\One.txt') as mytext:
    a = mytext.read()
    

In [3]:
a

'This is a story about dogs\nour canine pets\nDogs are furry animals\n'

In [4]:
print(a)

This is a story about dogs
our canine pets
Dogs are furry animals



In [7]:
# To return each line in text as text

with open(r'C:\Users\natas\Downloads\UNZIP_FOR_NOTEBOOKS_FINAL\18-Naive-Bayes-and-NLP\One.txt') as mytext:
    #a = mytext.readlines()
    a = mytext.read()

In [8]:
a

'This is a story about dogs\nour canine pets\nDogs are furry animals\n'

In [9]:
a.lower().split()   # To separate every word in text and store in list

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [10]:
# IDEA OF VOCABULARY , get the unique values in every text
with open(r'C:\Users\natas\Downloads\UNZIP_FOR_NOTEBOOKS_FINAL\18-Naive-Bayes-and-NLP\One.txt') as mytext:
   
    words_one = mytext.read().lower().split()
    words_one = set(words_one)

In [11]:
words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [12]:
with open(r'C:\Users\natas\Downloads\UNZIP_FOR_NOTEBOOKS_FINAL\18-Naive-Bayes-and-NLP\Two.txt') as mytext:
   
    words_two = mytext.read().lower().split()
    words_two = set(words_two)

In [15]:
all_words = set()

In [16]:
all_words.update(words_one)

In [17]:
all_words.update(words_two)

In [18]:
all_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [19]:
full_dict = dict()
i = 0

for word in all_words:
    full_dict[word]= i
    i += 1

In [20]:
full_dict

{'sport': 0,
 'pets': 1,
 'canine': 2,
 'this': 3,
 'our': 4,
 'a': 5,
 'dogs': 6,
 'is': 7,
 'are': 8,
 'waves': 9,
 'fun': 10,
 'catching': 11,
 'about': 12,
 'water': 13,
 'popular': 14,
 'surfing': 15,
 'animals': 16,
 'story': 17,
 'furry': 18}

In [21]:
one_freq = [0]* len(full_dict)
two_freq = [0]* len(full_dict)
all_freq = [''] * len(full_dict)


In [22]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [24]:
with open(r'C:\Users\natas\Downloads\UNZIP_FOR_NOTEBOOKS_FINAL\18-Naive-Bayes-and-NLP\One.txt') as f:
    one_words = f.read().lower().split()

In [27]:
for word in one_words:
    word_ind = full_dict[word]
    one_freq[word_ind] += 1

In [28]:
one_freq

[0, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1]

In [29]:
with open(r'C:\Users\natas\Downloads\UNZIP_FOR_NOTEBOOKS_FINAL\18-Naive-Bayes-and-NLP\Two.txt') as f:
    two_words = f.read().lower().split()

In [30]:
for word in two_words:
    word_ind = full_dict[word]
    two_freq[word_ind] += 1

In [31]:
two_freq

[1, 0, 0, 1, 0, 1, 0, 3, 0, 1, 1, 1, 1, 1, 1, 2, 0, 1, 0]

In [33]:
for word in full_dict:
    word_ind = full_dict[word]
    all_freq[word_ind]= word

In [34]:
all_freq

['sport',
 'pets',
 'canine',
 'this',
 'our',
 'a',
 'dogs',
 'is',
 'are',
 'waves',
 'fun',
 'catching',
 'about',
 'water',
 'popular',
 'surfing',
 'animals',
 'story',
 'furry']

In [36]:
import pandas as pd
bow = pd.DataFrame(data = [one_freq, two_freq], columns = all_freq)
bow

sport  pets  canine  this  our  a  dogs  is  are  waves  fun  catching  \
0      0     1       1     1    1  1     2   1    1      0    0         0   
1      1     0       0     1    0  1     0   3    0      1    1         1   

   about  water  popular  surfing  animals  story  furry  
0      1      0        0        0        1      1      1  
1      1      1        1        2        0      1      0

In [61]:
# Process above was just manually setting
# Now go on with Scikit learn
text = ['This is a line',
           "This is another line",
       "Completely different line"]

In [62]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
cv = CountVectorizer()

In [66]:
sparse_matrix = cv.fit_transform(text)

In [67]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [68]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [54]:
cv.vocabulary_   # THIS STATEMENT IS DIRECTLY ON COUNTVECTORIZER(ON INSTANCE)

{'line': 2, 'completely': 0, 'different': 1}

In [69]:
tfidf = TfidfTransformer()

In [71]:
results = tfidf.fit_transform(sparse_matrix)

In [73]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [74]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [75]:
tv = TfidfVectorizer()

In [76]:
res = tv.fit_transform(text)

In [77]:
res.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])